### PR TITLE
Security

### PR DESCRIPTION
**Pull request by aochagavia**
Refactoring, fix unauthorized access errors, add BCrypt hashing, remove password logging

### CODE REVIEW

**Comment by cataphract** [comment]
You're reinventing the wheel here. In you simple scenario,  where you're just authenticating against a database table, you only need to have a bean implementing `UserDetailsService`  (or not even that, if you can get by using `JdbcUserDetailsManager`, which also handles user management).

**Comment by gijskant** [comment]
We are using a UserDetailsService, but there were some specific requirements regarding account blocking after failed attempts.

**Comment by cataphract** [comment]
You still don't need to implement an authentication provider for that, the `UserDetailsService` can indicate that the account is locked. See for instance how Ruslan did it for transmart: https://github.com/transmart/transmartApp/commit/9fedf6ba6de6e49e8d7b31fa32a504d3b08bcfb9

**Comment by gijskant** [comment]
Looks nice, indeed.

**Pull request merged**
